"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TECHNOLOGIES_STARTED = exports.TECHNOLOGIES_RECEIVED = void 0;
var TECHNOLOGIES_RECEIVED = 'TECHNOLOGIES_RECEIVED';
exports.TECHNOLOGIES_RECEIVED = TECHNOLOGIES_RECEIVED;
var TECHNOLOGIES_STARTED = 'TECHNOLOGIES_STARTED';
exports.TECHNOLOGIES_STARTED = TECHNOLOGIES_STARTED;